export { getDeleteAuthDeleteAccountUrl, deleteAuthDeleteAccount } from './deleteAuthDeleteAccount.ts'
export { getDeletePrescriptionsIdUrl, deletePrescriptionsId } from './deletePrescriptionsId.ts'
export { getGetAuthProfileUrl, getAuthProfile } from './getAuthProfile.ts'
export { getGetPrescriptionsUrl, getPrescriptions } from './getPrescriptions.ts'
export { getPostAuthSignInUrl, postAuthSignIn } from './postAuthSignIn.ts'
export { getPostAuthSignUpUrl, postAuthSignUp } from './postAuthSignUp.ts'
export { getPostPrescriptionsUrl, postPrescriptions } from './postPrescriptions.ts'
export { getPutPrescriptionsIdUrl, putPrescriptionsId } from './putPrescriptionsId.ts'